### ISSUE TITLE
PR 4.3.2 does not work on Java 1.6

### ISSUE THREAD

**Issue by ChrisSTARS2407** [MrTJP/ProjectRed#364]
It says, that the class is unsupported. Java version 1.6.0_65 by Apple. OS: OS X 10.9.2. I can't install Java RE 7, because it's only 64-bit and unstable at the moment.
The same problem was with CB's mods, but after hotfix, it began working.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 16.03.14 9:32
Description: Initializing game

java.lang.NoClassDefFoundError: mrtjp/projectred/core/ItemPart
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2484)
    at java.lang.Class.getDeclaredMethods(Class.java:1827)
    at cpw.mods.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:328)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:517)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.ClassNotFoundException: mrtjp.projectred.core.ItemPart
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 36 more
Caused by: java.lang.UnsupportedClassVersionError: mrtjp/projectred/core/ItemPart : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
    ... 38 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2484)
    at java.lang.Class.getDeclaredMethods(Class.java:1827)
    at cpw.mods.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:328)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:517)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Mac OS X (x86_64) version 10.9.2
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 894002960 bytes (852 MB) / 1071579136 bytes (1021 MB) up to 1333460992 bytes (1271 MB)
    JVM Flags: 4 total; -Xincgc -Xms1024M -Xmx1280M -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 Optifine OptiFine_1.6.4_HD_C8 87 mods loaded, 87 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{6.4.49.965} [Forge Mod Loader](minecraftforge-9.11.1.965.jar) Unloaded->Constructed
    Forge{9.11.1.965} [Minecraft Forge](minecraftforge-9.11.1.965.jar) Unloaded->Constructed
    CodeChickenCore{0.9.0.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    HeldCore-Core{01.03.06.00} [HeldCore-Core](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.6.1.9} [Not Enough Items](NotEnoughItems 1.6.1.9.jar) Unloaded->Constructed
    AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed
    DamageIndicatorsMod{2.9.2.3} [Damage Indicators](1.6.4 DamageIndicatorsv2.9.2.3.zip) Unloaded->Constructed
    bspkrsCore{v5.3(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev5.3.zip) Unloaded->Constructed
    ArmorStatusHUD{v1.15(1.6.4)} [ArmorStatusHUD]([1.6.4]ArmorStatusHUDv1.15.zip) Unloaded->Constructed
    Schematica{1.5.3.57} [Schematica]([1.6.4]Schematica.jar) Unloaded->Constructed
    StatusEffectHUD{v1.19(1.6.4)} [StatusEffectHUD]([1.6.4]StatusEffectHUDv1.19.zip) Unloaded->Constructed
    TreeCapitator{Forge 1.6.4.r09} [Treecapitator]([1.6.4]TreeCapitator.Forge.1.6.4.r09.Universal.zip) Unloaded->Constructed
    AppliedEnergistics{rv14.finale3} [Applied Energistics](appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed
    Autoutils{1.0.0} [Autoutils](autoutils-1.6.4-1.0.0.jar) Unloaded->Constructed
    iChunUtil{2.4.0} [iChunUtil](iChunUtil2.4.0.zip) Unloaded->Constructed
    BackTools{2.0.1} [BackTools](BackTools2.0.1.zip) Unloaded->Constructed
    CoFHCore{2.0.0.2} [CoFH Core](CoFHCore-2.0.0.2.jar) Unloaded->Constructed
    ForgeMultipart{1.0.0.244} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    ThermalExpansion{3.0.0.2} [Thermal Expansion](ThermalExpansion-3.0.0.2.jar) Unloaded->Constructed
    IC2{2.0.397-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.397-experimental.jar) Unloaded->Constructed
    Forestry{2.3.1.1} [Forestry for Minecraft](forestry-A-2.3.1.1.jar) Unloaded->Constructed
    BinnieCore{1.8.0} [Binnie Core](binnie-mods-1.8.0.jar) Unloaded->Constructed
    ExtraBees{1.8.0} [Extra Bees](binnie-mods-1.8.0.jar) Unloaded->Constructed
    ExtraTrees{1.8.0} [Extra Trees](binnie-mods-1.8.0.jar) Unloaded->Constructed
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    mod_CameraStudio{V2.164 (for Minecraft 1.6.4)} [mod_CameraStudio](CameraStudioV2.164%28mc1.6.4%29.zip) Unloaded->Constructed
    CarpentersBlocks{2.0.4} [Carpenter's Blocks](Carpenter's Blocks v2.0.4 - MC 1.6+.zip) Unloaded->Constructed
    ChickenChunks{1.3.3.4} [ChickenChunks](ChickenChunks 1.3.3.4.jar) Unloaded->Constructed
    Chisel{1.5.0} [Chisel](chisel-1.6.4-1.5.0.jar) Unloaded->Constructed
    CoFHLoot{2.0.0.2} [CoFH Loot](CoFHCore-2.0.0.2.jar) Unloaded->Constructed
    CoFHMasquerade{2.0.0.2} [CoFH Masquerade](CoFHCore-2.0.0.2.jar) Unloaded->Constructed
    CoFHSocial{2.0.0.2} [CoFH Social](CoFHCore-2.0.0.2.jar) Unloaded->Constructed
    CoFHWorld{2.0.0.2} [CoFH World](CoFHCore-2.0.0.2.jar) Unloaded->Constructed
    ComputerCraft{1.58} [ComputerCraft](ComputerCraft1.58.zip) Unloaded->Constructed
    CCTurtle{1.58} [ComputerCraft Turtles](ComputerCraft1.58.zip) Unloaded->Constructed
    DynamicLights{1.2.8} [Dynamic Lights](DynamicLights_1.6.4.jar) Unloaded->Constructed
    DynamicLights_onFire{1.0.3} [Dynamic Lights on burning](DynamicLights_1.6.4.jar) Unloaded->Constructed
    DynamicLights_creepers{1.0.3} [Dynamic Lights on Creepers](DynamicLights_1.6.4.jar) Unloaded->Constructed
    DynamicLights_dropItems{1.0.5} [Dynamic Lights on ItemEntities](DynamicLights_1.6.4.jar) Unloaded->Constructed
    DynamicLights_entityClasses{1.0.0} [Dynamic Lights on specified Entities](DynamicLights_1.6.4.jar) Unloaded->Constructed
    DynamicLights_mobEquipment{1.0.3} [Dynamic Lights on Mob Equipment](DynamicLights_1.6.4.jar) Unloaded->Constructed
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights on Flame enchanted Arrows](DynamicLights_1.6.4.jar) Unloaded->Constructed
    DynamicLights_otherPlayers{1.0.5} [Dynamic Lights Other Player Light](DynamicLights_1.6.4.jar) Unloaded->Constructed
    DynamicLights_thePlayer{1.0.9} [Dynamic Lights Player Light](DynamicLights_1.6.4.jar) Unloaded->Constructed
    EnderIO{0.11.1} [Ender IO](EnderIO-1.6.4-0.11.1.315.jar) Unloaded->Constructed
    EnderStorage{1.4.3.6} [EnderStorage](EnderStorage 1.4.3.6.jar) Unloaded->Constructed
    GregsLighting{1.9.1} [Greg's Lighting](GregsLighting-1.9.1-mc1.6.4.jar) Unloaded->Constructed
    Railcraft{8.4.0.0} [Railcraft](Railcraft_1.6.4-8.4.0.0.jar) Unloaded->Constructed
    gregtech_addon{MC162} [GregTech-Addon](gregtechmod-4.08s.zip) Unloaded->Constructed
    HeldCore{01.03.06.00} [HeldCore](HeldCore-1.6.4-01.03.06.00.jar) Unloaded->Constructed
    IC2NuclearControl{1.6.2e} [Nuclear Control](IC2NuclearControl-1.6.2e-ic2-experimental.zip) Unloaded->Constructed
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed
    IronChest{5.4.1.702} [Iron Chest](ironchest-universal-1.6.4-5.4.1.702.zip) Unloaded->Constructed
    LightBridgesAndDoors{0.1.7} [kris91268's Light Bridges and Doors](Light bridges and doors V1.7.zip) Unloaded->Constructed
    LogisticsPipes|Main{0.7.4.dev.113} [Logistics Pipes](LogisticsPipes-MC1.6.4-0.7.4.dev.113.jar) Unloaded->Constructed
    GraviSuite{1.9.8} [Gravitation Suite](mod_zGraviSuite_1_9_8_MC_1_6_4_IC_EXP.zip) Unloaded->Constructed
    Mystcraft{0.10.10.00} [Mystcraft](mystcraft-uni-1.6.4-0.10.10.00.zip) Unloaded->Constructed
    Natura{2.1.14} [Natura](Natura_mc1.6.X_2.1.14.jar) Unloaded->Constructed
    NEIAddons{1.10.4.64} [NEI Addons](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
    NEIAddons|AE{1.10.4.64} [NEI Addons: Applied Energistics](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
    NEIAddons|MiscPeripherals{1.10.4.64} [NEI Addons: Misc Peripherals](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
    NEIAddons|ExtraBees{1.10.4.64} [NEI Addons: Extra Bees](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
    NEIAddons|Forestry{1.10.4.64} [NEI Addons: Forestry](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
    NEIAddons|CraftingTables{1.10.4.64} [NEI Addons: Crafting Tables](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
    NEIPlugins{1.1.0.6} [NEI Plugins](NEIPlugins-1.1.0.6.jar) Unloaded->Constructed
    ParachuteMod{1.6.4} [Parachute Mod](parachute-2.0.2-1.6.4.jar) Unloaded->Constructed
    PortalGun{2.0.2} [PortalGun](PortalGun2.0.2.zip) Unloaded->Constructed
    ProjRed|Core{4.3.2.26} [ProjectRed](ProjectRedBase-1.6.4-4.3.2.26.jar) Unloaded
    ProjRed|Integration{4.3.2.26} [ProjectRed-Integration](ProjectRedIntegration-1.6.4-4.3.2.26.jar) Unloaded
    ProjRed|Transmission{4.3.2.26} [ProjectRed-Transmission](ProjectRedIntegration-1.6.4-4.3.2.26.jar) Unloaded
    ProjRed|Illumination{4.3.2.26} [ProjectRed-Illumination](ProjectRedLighting-1.6.4-4.3.2.26.jar) Unloaded
    ProjRed|Transportation{4.3.2.26} [ProjectRed-Transportation](ProjectRedMechanical-BETA-1.6.4-4.3.2.26.jar) Unloaded
    ProjRed|Expansion{4.3.2.26} [ProjectRed-Expansion](ProjectRedMechanical-BETA-1.6.4-4.3.2.26.jar) Unloaded
    ProjRed|Exploration{4.3.2.26} [ProjectRed-Exploration](ProjectRedWorld-1.6.4-4.3.2.26.jar) Unloaded
    StevesCarts{2.0.0.b10} [Steve's Carts 2](StevesCarts2.0.0.b10.zip) Unloaded
    TwilightForest{1.20.4} [The Twilight Forest](twilightforest-1.6.4-1.20.4.jar) Unloaded
    Waila{1.5.1} [Waila](Waila_1.5.1a.zip) Unloaded
    mod_ZanMinimap{Not available} [mod_ZanMinimap](ZansMinimap1.6.4.zip) Unloaded
    McMultipart{1.0.0.244} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded
    NEI-Mystcraft-Plugin{01.05.00.00} [NEI Mystcraft Plugin](MystNEI-Plugin-1.6.4-01.05.00.00.zip) Unloaded
    ForgeMicroblock{1.0.0.244} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded
    Launched Version: 1.6.4-Forge9.11.1.965
    LWJGL: 2.9.0
    OpenGL: Intel HD Graphics 3000 OpenGL Engine GL version 2.1 INTEL-8.24.11, Intel Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: faithful32pack.zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
